swagger: '2.0'
info:
  description: Schroedinger's REST API documentation
  version: 1.0.0
  title: Schroedinger API
  contact:
    email: you@schroedinger.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
- name: user
- name: survey
- name: submission
paths:

# User path
  /{reCaptcha token}:
    post:
      tags:
      - user
      summary: create a new user account 
      produces:
      - application/json
      parameters:
      - in: path
        name: reCaptcha token
        type: string
        required: true
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserRegistration'
      responses:
        201:
          description: User created
        400:
          description: User could not be created
        409: 
          description: Username and/or email allready exist
  /login:        
    post:
      tags:
      - user
      summary: user login with given credentials
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserLogin'
      responses:
        200:
          description: User login ok
          schema:
            $ref: '#/definitions/ExampleToken'
        400: 
          description: Wrong credentials
              
# Survery path
  /survey:
    post:
      tags:
      - survey
      summary: user creates a new survey
      parameters:
      - in: header
        name: Authorization
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateSurvey'
      responses:
        201:
          description: Survey was created
          schema:
            $ref: '#/definitions/SurveyResponse'
        400:
          description: could not be created
  /survey/{survey_id}:        
    get:
      tags:
      - survey
      summary: a specific survey is fetched
      parameters:
      - in: header
        name: Authorization
        required: true
        type: string
      - in: path
        name: survey_id
        required: true
        type: string
      responses:
        200:
          description: requested survey is available
          schema:
            items: 
              $ref: '#/definitions/RequestedSurvey'
        400:
          description: survey not available
  
  /survey/search:
    get:
      tags:
      - survey
      summary: retrieves a survey, based on a search term
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/SearchString'
      responses:
        200:
          description: survey matching the search term was found
          schema:
            $ref: '#/definitions/UserSurvey'
        
  
  /survey/owner:
    get: 
      tags: 
      - survey
      summary: all survey belonging to the user are fetched
      parameters:
      - in: header
        name: Authorization
        required: true
        type: string
      responses:
        200:
          description: all surveys belonging to the user
          schema:
            $ref: '#/definitions/RequestedSurvey'
            
  /survey/user/{private_survey_token}:
    get:
      tags: 
      - survey
      summary: a survey was opened trough a link
      parameters:
      - in: query
        name: survey_id
        required: true
        type: string
      - in: path
        required: true
        name: private_survey_token
        type: string
      responses:
        200: 
          description: survey is active
          schema:
            $ref: '#/definitions/UserSurvey'
        403:
          description: user not allowed to see survey, token already used
        400:
          description: survey not active, ended or did not start yet
            
  /submission/survey:          
    post:
      tags:
      - submission
      summary: user took a survey and submits it 
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserSurvey'
      responses:
        200: 
          description: answered survey was handed in
        400: 
          description: answers to survey could not be persisted

# Defintions of request and response objects
definitions:
# Search String
  SearchString:
    type: object
    required: 
    - search
    properties:
      search:
        type: string
        example: 'SearchString'
# Token
  ExampleToken:
    type: object
    required: 
    - token
    properties:
      token:
        type: string
        example: 'exampleJWTtoken'
        
# Links
  ExampleLink:
    type: object
    required: 
    - link
    properties:
      link:
        type: string
        example: 'https://schroedingers-survey.de/HJD9fhdkish349GHDGszh4hkfhs'

# User related
  UserRegistration:
    type: object
    required:
    - username
    - password
    - email
    properties:
      username:
        type: string
        example: maxmustermann
      password:
        type: string
        example: astrongpassword
      email:
        type: string
        example: maxmustermann@contact.de
  UserLogin:
    type: object
    required:
    - username
    - password
    properties:
      username:
        type: string
        example: maxmustermann
      password:
        type: string
        example: astrongpassword 
        
# Survey related  
  SurveyResponse:
    type: object
    required: 
    - id
    - title
    - start date
    - end date
    - public
    - secure
    - links
    properties:
      id:
        type: string
        example: 'fgHd-73hg-83HZ'
      title:
        type: string
        example: 'Do you like cats'
      start-date:
        type: string
        example: '25.09.2020'
      end-date:
        type: string
        example: '25.10.2020'
      public:
        type: boolean
        example: true
      secured:
        type: boolean
        example: false
      links:
        type: array
        items:
          $ref: '#/definitions/ExampleLink'

  ConstrainedQuestion:
    type: object
    required:
      - title
      - position
      - options
    properties:
      title:
        type: string
        example: 'Do cats have fluffy fur?'
      position:
        type: number
        example: 2
      options:
        type: array 
        items:
          $ref: '#/definitions/ConstrainedOption'
          
  ConstrainedOption:
    type: object
    required: 
      - name
    properties:
      name:
        type: string
        example: 'Very much'        
  
  FreestyleQuestion:
    type: object
    required: 
      - title
      - position
    properties:
      title:
        type: string
        example: 'Do cats have fluffy fur?'
      position:
        type: number
        example: 2
        
  QuestionForUser:
    type: object
    required:
      - id
      - title
      - constrained-options
    properties:
      id:
        type: string
        example: 'fgHd-73hg-83HZ'
      title:
        type: string
        example: 'I like cats'
      constrained-options:
        type: array 
        items:
          $ref: '#/definitions/ConstrainedOption'
        
        
  AnswerdedConstrainedQuestion:
    type: object
    required: 
      - survey_id
      - question_id
      - question-option
    properties:
      survey_id:
        type: string
        example: 'd44f-73hg-83HZ'
      constrained-question_id:
        type: string
        example: '2Fsd-73hg-83HZ'
      constrained-question-option:
        type: string
        example: 'fL9d-73hg-83HZ'  
        
  AnswerdedFreestyleQuestion:
    type: object
    required:
      - survey-question_id
      - freestyle-answers
    properties:
      survey-question_id:
        type: string
        example: 'fgHd-73hg-83HZ'
      freestyle-answers:
        type: string
        example: 'Not that much, they scratch me often,so no'        
        
        
  CreateSurvey:
    type: object
    required:
    - title
    - description
    - start-date
    - end-date
    - public
    - secured
    - constrained_questions
    - freestyle_questions
    properties:
      title:
        type: string
        example: 'Experience when working with Schroedinger'
      description:
        type: string
        example: 'The result of this survey is used to improve the user experience of this app'
      start-date:
        type: string
        example: '25.09.2020'
      end-date:
        type: string
        example: '25.10.2020'
      public:
        type: boolean
        example: true
      secured:
        type: boolean
        example: false
      constrained_questions:
        type: array
        items:
          $ref: '#/definitions/ConstrainedQuestion'
      freestyle_questions:
        type: array
        items:
          $ref: '#/definitions/FreestyleQuestion'
          
  RequestedSurvey:
    type: object
    required:
    - title
    - description
    - start-date
    - end-date
    - public
    - secured
    - constrained_questions
    - freestyle_questions
    properties:
      title:
        type: string
        example: 'Experience when working with Schroedinger'
      description:
        type: string
        example: 'The result of this survey is used to improve the user experience of this app'
      start-date:
        type: string
        example: '25.09.2020'
      end-date:
        type: string
        example: '25.10.2020'
      public:
        type: boolean
        example: true
      secured:
        type: boolean
        example: false
      constrained_questions:
        type: array
        items: 
          $ref: '#/definitions/AnswerdedConstrainedQuestion'
      freestyle_questions:
        type: array
        items:
          $ref: '#/definitions/AnswerdedFreestyleQuestion'
          
          
  UserSurvey:
    type: object
    required:
    - survey_id
    - title
    - start-date
    - end-date
    - description
    - constrained_answers
    - freestyle_answers
    properties:
      survey_id:
        type: string
        example: 'fgHd-73hg-83HZ'
      title:
        type: string
        example: 'Experience when working with Schroedinger'
      start-date:
        type: string
        example: '25.09.2020'
      end-date:
        type: string
        example: '25.10.2020'  
      description:
        type: string
        example: 'The result of this survey is used to improve the user experience of this app'
      constrained_answers:
        type: array
        items:
          $ref: '#/definitions/ConstrainedQuestion'
      freestyle_answers:
        type: array
        items: 
          $ref: '#/definitions/FreestyleQuestion'
